#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | grep ".*\.rb$" | \
    ripper-tags --exclude=vendor --tag-relative --extra=q -L  - -f"$dir/$$.tags"
git ls-files | \
  "${CTAGS:-ctags}" -a --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql,ruby
mv "$dir/$$.tags" "$dir/tags"
