#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="$(git rev-parse --git-dir)"
trap 'rm -f "$dir/$$.ctags" "$dir/$$.rtags"' EXIT

git ls-files | \
  "${CTAGS:-ctags}" --tag-relative -L - -f"$dir/$$.ctags" --languages=-javascript,sql,ruby
ripper-tags --exclude=vendor --tag-relative -R -f"$dir/$$.rtags"
cat "$dir/$$.ctags" "$dir/$$.rtags" > "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
