#!/bin/bash

protected_branch='refs/heads/master'

# shellcheck disable=SC2034
while read -r _local_ref _local_sha remote_ref _remote_sha
do
  if [ "$remote_ref" == "$protected_branch" ]
  then
    read -p "WARNING: You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo "$REPLY" | grep -E '^[Yy]$' > /dev/null
    then
      exit 0 # push will execute
    fi
    exit 1 # push will not execute
  else
    exit 0 # push will execute
  fi
done
